Treasure567
kelue/apexHauz pull request #23
Opened 2022-05-12 22:30 UTC by treasure567

User can login and Register

2022-05-14 12:12 UTC, ahmadinjo requested changes

2022-05-14 12:57 UTC, treasure567 commented on src/database/queries.js
> +    title VARCHAR(255) NOT NULL,
I was following specifications given from the capstone

2022-05-14 12:58 UTC, treasure567 commented on src/database/queries.js
> +    name VARCHAR(255) NOT NULL UNIQUE,
Ok cool

2022-05-14 12:58 UTC, treasure567 commented on src/database/queries.js
> +    description VARCHAR(255) DEFAULT NULL,
Noted. Will update

2022-05-14 12:58 UTC, treasure567 commented on src/database/queries.js
> +    image VARCHAR(255) DEFAULT NULL,
Ok boss

2022-05-14 13:03 UTC, ahmadinjo commented on src/database/queries.js
> +    title VARCHAR(255) NOT NULL,
No problem then. Leave it at that

2022-05-14 14:54 UTC, treasure567 commented
@kelue Review and approve

2022-05-14 17:43 UTC, kelue approved these changes
Looks good

2022-05-15 10:39 UTC, ahmadinjo approved these changes
Good work boss. I have effect some changes in my pull request too, you can check them out

2022-05-15 11:08 UTC, merged